---
wireless:
  - key: ssid
    value: CEROwrt
    ifaces: [0]
  - key: ssid
    value: CEROwrt5
    ifaces: [3]
  - key: encryption
    value: psk2
    ifaces: [0,3]
  - key: key
    value: Beatthebloat
    ifaces: [0,3]
  - key: ssid
    value: CEROwrt-guest
    ifaces: [1]
  - key: ssid
    value: CEROwrt-guest5
    ifaces: [4]
  - key: encryption
    value: none
    ifaces: [1,4]
  - key: key
    value: ""
    ifaces: [1,4]
