---
- name: apply firewall default policies
  uci: command=set key="firewall.@defaults[0].{{ item.key }}" value="{{ item.value }}"
  with_dict:
    input: REJECT
    forward: REJECT
    output: ACCEPT
  notify:
    - uci commit
    - reload firewall

- name: apply firewall zone policies
  uci: command=set key="firewall.@zone[{{ item.1 }}].{{ item.0.chain }}" value="{{ item.0.policy }}"
  with_subelements:
    - firewall.policies
    - zone
  notify:
    - uci commit
    - reload firewall


- name: firewall forwarding policies (prepare)
  uci: command=set key="firewall.@forwarding[{{ item.index }}]" value="forwarding"
  with_items:
    firewall.forwarding
  notify:
    - uci commit
    - reload firewall

- name: firewall forwarding policies
  uci: command=set key="firewall.@forwarding[{{ item.0.index }}].{{ item.1.key }}" value="{{ item.1.value }}"
  with_subelements:
    - firewall.forwarding
    - settings
  notify:
    - uci commit
    - reload firewall


- name: firewall redirect rules (prepare)
  uci: command=set key="firewall.@redirect[{{ item.index }}]" value="redirect"
  with_items:
    firewall.redirect
  notify:
    - uci commit
    - reload firewall

- name: firewall redirect rules
  uci: command=set key="firewall.@redirect[{{ item.0.index }}].{{ item.1.key }}" value="{{ item.1.value }}"
  with_subelements:
    - firewall.redirect
    - settings
  notify:
    - uci commit
    - reload firewall
